version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      - echo Installing dependencies...
      - cd ui  
      - npm install 
  pre_build:
    commands:
      - echo Pre-building the application...

  build:
    commands:
      - echo Building the application...
      - npm run build 
      - echo Starting the server...
      - chmod +x ./scripts/start_server.sh 
      - ./scripts/start_server.sh  

  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - ui/build/**/*  

cache:
  paths:
    - ui/node_modules/**/*
